apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 51.2.0
    helm:
      parameters:
        - name: prometheus.prometheusSpec.ruleSelectorNilUsesHelmValues
          value: "false"
        - name: prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues
          value: "false"
        - name: prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues
          value: "false"
        - name: prometheus.prometheusSpec.probeSelectorNilUsesHelmValues
          value: "false"
        - name: alertmanager.enabled
          value: "false"
        - name: prometheusOperator.admissionWebhooks.enabled
          value: "false"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
